import { Router } from 'express';

import { accessControlRouter } from '../modules/access-control/access-control.router.js';
import { auditRouter } from '../modules/audit/audit.router.js';
import { authRouter } from '../modules/auth/auth.router.js';
import { branchesRouter } from '../modules/branches/branches.router.js';
import { cashRegisterRouter } from '../modules/cash-register/cash-register.router.js';
import { classesRouter } from '../modules/classes/classes.router.js';
import { clientsRouter } from '../modules/clients/clients.router.js';
import { dashboardRouter } from '../modules/dashboard/dashboard.router.js';
import { expensesRouter } from '../modules/expenses/expenses.router.js';
import { financeRouter } from '../modules/finance/finance.router.js';
import { membershipsRouter } from '../modules/memberships/memberships.router.js';
import { notificationsRouter } from '../modules/notifications/notifications.router.js';
import { paymentsRouter } from '../modules/payments/payments.router.js';
import { plansRouter } from '../modules/plans/plans.router.js';
import { productsRouter } from '../modules/products/products.router.js';
import { reportsRouter } from '../modules/reports/reports.router.js';
import { settingsRouter } from '../modules/settings/settings.router.js';
import { usersRouter } from '../modules/users/users.router.js';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/branches', branchesRouter);
apiRouter.use('/settings', settingsRouter);
apiRouter.use('/clients', clientsRouter);
apiRouter.use('/plans', plansRouter);
apiRouter.use('/memberships', membershipsRouter);
apiRouter.use('/payments', paymentsRouter);
apiRouter.use('/expenses', expensesRouter);
apiRouter.use('/cash-register', cashRegisterRouter);
apiRouter.use('/finance', financeRouter);
apiRouter.use('/reports', reportsRouter);
apiRouter.use('/products', productsRouter);
apiRouter.use('/classes', classesRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/access-control', accessControlRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/audit', auditRouter);
